steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-node-app:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/my-node-app:$COMMIT_SHA'

images:
  - 'gcr.io/$PROJECT_ID/my-node-app:$COMMIT_SHA'

options:
  logging: NONE  # Disable build logging
